S2SRefreshBundle:
    resource: "@S2SRefreshBundle/Resources/config/routing.yml"
    prefix:   /

FoundershubStartupWeekendBundle:
    resource: "@FoundershubStartupWeekendBundle/Resources/config/routing.yml"
    prefix:   /

DothivContentfulBundle:
    resource: "@DothivContentfulBundle/Resources/config/routing.yml"
    prefix:   /contentful/
