parameters:
#    s2_s_refresh.example.class: S2S\RefreshBundle\Example

services:
#    s2_s_refresh.example:
#        class: %s2_s_refresh.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
